### ISSUE TITLE
Re-enable releaseEarlyEnableSyncToMaven

### ISSUE THREAD

**Issue by kwark** [kwark/play-refined#2]
But this gives a problem when syncing from bintray to sonatype because sonatype credentials need to be provided, somehow:

java.lang.RuntimeException: Credentials file /home/travis/.bintray/.credentials does not exist
	at scala.sys.package$.error(package.scala:27)
	at sbt.Credentials$.toDirect(Credentials.scala:30)
	at sbt.Credentials$$anonfun$allDirect$1.apply(Credentials.scala:26)
	at sbt.Credentials$$anonfun$allDirect$1.apply(Credentials.scala:26)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at sbt.Credentials$.allDirect(Credentials.scala:26)
	at sbt.Credentials$.forHost(Credentials.scala:25)
	at bintray.BintrayRepo.resolveSonatypeCredentials(BintrayRepo.scala:159)
	at bintray.BintrayRepo.syncMavenCentral(BintrayRepo.scala:138)
	at bintray.BintrayPlugin$$anonfun$bintrayPublishSettings$19.apply(BintrayPlugin.scala:111)
	at bintray.BintrayPlugin$$anonfun$bintrayPublishSettings$19.apply(BintrayPlugin.scala:109)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by kwark** [comment]
switched to sbt-ci-release
