### ISSUE TITLE
SIRDServerSuite sometimes fails on travis

### ISSUE THREAD

**Issue by kwark** [kwark/play-refined#51]
[info] be.venneborg.refined.play.SIRDServerSuite *** ABORTED ***
[info]   play.core.server.ServerListenException: Failed to listen for HTTP on /0.0.0.0:9000!
[info]   at play.core.server.NettyServer.play$core$server$NettyServer$$bindChannel(NettyServer.scala:231)
[info]   at play.core.server.NettyServer$$anonfun$2.apply(NettyServer.scala:219)
[info]   at play.core.server.NettyServer$$anonfun$2.apply(NettyServer.scala:219)
[info]   at scala.Option.map(Option.scala:146)
[info]   at play.core.server.NettyServer.<init>(NettyServer.scala:219)
[info]   at play.core.server.NettyServerComponents$class.server(NettyServer.scala:370)
[info]   at play.core.server.NettyServer$$anon$1.server$lzycompute(NettyServer.scala:356)
[info]   at play.core.server.NettyServer$$anon$1.server(NettyServer.scala:356)
[info]   at play.core.server.NettyServer$.createServerFromRouter(NettyServer.scala:359)
[info]   at play.core.server.ServerFromRouter$class.fromRouterWithComponents(Server.scala:329)
[info]   ...

**Comment by kwark** [comment]
Maybe look in to the possibility to start play on a random free port ?
